spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/loop-erp
spring.datasource.username=admin-user
spring.datasource.password=eRmUstrI

kafka.bootstrap-servers=localhost:9092