#YAML
version: '3.8'

services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: erp-postgres
    environment:
      - 'POSTGRES_DB=loop-erp'
      - 'POSTGRES_PASSWORD=eRmUstrI'
      - 'POSTGRES_USER=admin-user'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin-user -d loop-erp"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - loop-erp-network

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.6.0'
    container_name: erp-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - loop-erp-network

  kafka:
    image: 'confluentinc/cp-kafka:7.6.0'
    container_name: erp-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka:29092,INTERNAL://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - loop-erp-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - loop-erp-network

  adminer:
    image: adminer
    container_name: erp-adminer
    ports:
      - "8081:8080"
    networks:
      - loop-erp-network

  prometheus:
    image: prom/prometheus:latest
    container_name: erp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - loop-erp-network

  grafana:
    image: grafana/grafana:latest
    container_name: erp-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - loop-erp-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Desabilitado para ambiente de desenvolvimento local
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - mem_limit=768m
    ports:
      - "9200:9200"
    networks:
      - loop-erp-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000/tcp" # Porta para receber logs dos microsserviços
      - "5000:5000/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - loop-erp-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - loop-erp-network

  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    networks:
      - loop-erp-network

  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    container_name: teamcity-agent
    privileged: true # Necessário para o container conseguir rodar os binários do Docker
    user: root # Garante permissão total para acessar o docker.sock
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - DOCKER_IN_DOCKER=start
    volumes:
      - teamcity_agent_conf:/data/teamcity_agent/conf
      # Muito importante: Isso permite que o Agente do TeamCity rode comandos Docker (como o seu docker build)
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - teamcity-server
    networks:
      - loop-erp-network


volumes:
  pg_data:
  kafka_data:
  prometheus_data:
  grafana_data:
  teamcity_server_data:
  teamcity_server_logs:
  teamcity_agent_conf:

networks:
  loop-erp-network:
    driver: bridge