input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Aqui você pode adicionar filtros para estruturar melhor seus logs, se necessário
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "erp-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Útil para ver os logs no console do Docker enquanto configura
}