package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("env.QODANA_TOKEN", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiNDBXeW8iLCJvcmdhbml6YXRpb24iOiI1Wnh4RCIsInRva2VuIjoiWU9RT2EifQ.DbdWg2Qk0MjC-HdE6RbzygkYluJwMnitUsdbLMwW0T4")
        }
    }
}
