spring:
  application:
    name: gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.requestedTokens: 1
#                    redis-rate-limiter.replenishRate: 20
#                    redis-rate-limiter.burstCapacity: 10
#                    key-resolver: "#{@ipKeyResolver}"
            - id: billing-service
              uri: lb://billing-service
              predicates:
                - Path=/billing/**
              filters:
                - StripPrefix=1
            - id: cadastro-service
              uri: lb://cadastro-service
              predicates:
                - Path=/api/**
#              filters:
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.requestedTokens: 1
#                    redis-rate-limiter.replenishRate: 20
#                    redis-rate-limiter.burstCapacity: 10
#                    key-resolver: "#{@ipKeyResolver}"
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: DEBUG

api:
  security:
    jwt:
      secret: security-key-for-now

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
#cors.allowed-origins=http://localhost:4200,http://localhost:4201
#cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
#cors.allowed-headers=Authorization,Content-Type
#cors.allow-credentials=true
