spring.application.name=gateway

server.port=8090

# Auth Service (local)
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0]=PreserveHostHeader

api.security.jwt.secret=${JWT_SECRET}

spring.cloud.gateway.server.webmvc.routes[1].id=cadastro-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/cadastro/**

cors.allowed-origins=https://app.exemplo.com
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Content-Type,ngrok-skip-browser-warning
cors.allow-credentials=true

#SPRING_PROFILES_ACTIVE=prod