spring.application.name=gateway

server.port=8090

# Auth Service (local)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader

api.security.jwt.secret=security-key-for-now