spring.application.name=gateway

server.port=8090

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Auth Service (local)
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
#spring.cloud.gateway.server.webmvc.routes[0].filters[0]=PreserveHostHeader

api.security.jwt.secret=security-key-for-now

spring.cloud.gateway.server.webmvc.routes[1].id=cadastro-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://cadastro-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/**

#cors.allowed-origins=http://localhost:4200,http://localhost:4201
#cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
#cors.allowed-headers=Authorization,Content-Type
#cors.allow-credentials=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
#management.endpoint.metrics.enabled=true
#management.endpoint.metrics.export.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

logging.level.root=DEBUG
