spring.application.name=liquibase-service
spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/loop-erp
spring.datasource.username=admin-user
spring.datasource.password=eRmUstrI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=true