spring.application.name=liquibase-service

# Não subir servidor Web (Tomcat), pois é apenas um script de migração
spring.main.web-application-type=none

# Conexão com o Banco
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/loop-erp
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
# Drop first? CUIDADO: Só use true em dev se quiser limpar o banco sempre que rodar
spring.liquibase.drop-first=false